### ISSUE TITLE
Sklearn: No module named sklearn

### ISSUE THREAD

**Issue by eloyvaldera-te** [rimolive/zeppelin-openshift#1]
Hi!

I'm trying to use zeppelin to deploy a recommender system for machine learning purpose on Openshift. I'm getting "no module named sklearn" when I play my notebook, Is possible to install some python dependencies?

Thanks :)

**Comment by rimolive** [comment]
Maybe I need to find a way to install dependencies from other languages. As zeppelin supports a lot of interpreters the challenge will be to find a way to install the interpreter requirements just by looking the ZEPPELIN_INTERPRETERS param from the template.

**Comment by eloyvaldera-te** [comment]
Checking the original documentation (http://scikit-learn.org/stable/install.html) We need to install python modules like matplotlib, I think the best way to do this is create a new param named PYSPARK_MODULES to run pip install for each coma separeted value (not only for matplotlib)

Based on your s2i code:
```
if [[ ! "x$PYSPARK_MODULES" == "x" ]]; then
  echo "---> Installing additional python modules..."
  read -a py_modules<<< $(echo $PYSPARK_MODULES | sed 's/,/ /g' )

  for module in ${py_modules[@]}; do
    pip install $module
  done
fi
```

Thanks!

**Comment by eloyvaldera-te** [comment]
Hi! I'm working on it but is my first time deploying images with s2i and cekit. I hope to have good news soon!

**Comment by eloyvaldera-te** [comment]
Hi again! Everything is working but i'm getting some permissions errors

```
OSError: [Errno 13] Permission denied: '/usr/lib64/python2.7/site-packages/numpy-1.7.1-py2.7.egg-info'
```

I'm not sure if this directory is created using the same user or not. Checking your last commit, I see that you fixed some permission issues, could it be the same problem?.

**Comment by rimolive** [comment]
hmm, there shouldn't be a problem if you are running s2i assemble script, this should be running without problem. Can you post in pastebin.com the full output which contains the error?

**Comment by rimolive** [comment]
Oh, and if possible send me your branch with that custom code too.

**Comment by eloyvaldera-te** [comment]
Hi again! I dont't know a lot about s2i but may be assemble script is running using USER 185.

Right now, I'm running a working environment but is a workaround (I need a environment to Master's tesis) but when I finish I hope to troubleshoot all problems to make this working. Now, I'm including pip install for all modules that I need in file modules/pyspark/run (like matplotlib). Everythings is working as expected.

Here is my branch: https://github.com/eloyvaldera-te/zeppelin-openshift/tree/python_modules, as you can see, I only have added my code on s2i-interpreters module.

I will try to recreate this environment tomorrow and paste the full output

@elmiko I'm trying to do with pip command to be aligned with the current behavior. Now is using pip to install pip matplotlib, for sure your solution is much better so I will research about this.

**Comment by rimolive** [comment]
@elmiko @eloyvaldera-te I don't know if `pip` would be the solution as Zeppelin has something similar to Jupyter but using conda: https://zeppelin.apache.org/docs/0.8.0/interpreter/python.html#conda

Having that said, one option is to create an example using conda capabilities  to show how to install packages in zeppelin.
